version: '3.7'

services:
  fastapisql:
    build: .
    command: uvicorn sql_app.main:app --host 0.0.0.0 --port 80
    volumes:
      - /app
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kimtoan123
      - POSTGRES_DB=fastapisql
    expose:
      - 5432

volumes:
  postgres_data: